docker_path: 'docker'

# Number of GPUs to use
num_use_gpu: 1

# gitURL and branch of the project
git_url: 'https://github.com/tanimutomo/U-Net.git'
git_branch: 'master'

# project directory path
pj_root: '/home/tanimu/Project/kronos'

# The path of the project's data directory
data_dir: 'data'

# The path of the original data directory in the remote server you want to copy to the project's data directory
origin_data: '/home/tanimu/Project/data/VOC'

# If you fix the GPU server and GPU number you use, please specify them
fix_server: ''
fix_gpu: []

# ssh config path
ssh_config_path: '~/.ssh/config'
